version: '3.8'

services:
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on: [backend]

  backend:
    build: ./backend
    ports: ["8000:8000"]
    environment:
      - DATABASE_URL=postgresql://sentinel:password@postgres:5432/sentineldb
      - REDIS_URL=redis://redis:6379
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on: [postgres, redis]
    volumes:
      - ./backend/models:/app/models   # AI model weights

  ai_worker:
    build: ./backend
    command: celery -A tasks.celery_tasks worker --loglevel=info
    depends_on: [redis, backend]
    volumes:
      - ./backend/models:/app/models

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sentineldb
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  nginx:
    image: nginx:alpine
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: [frontend, backend]

volumes:
  postgres_data:
